---
- name: Install Fish shell
  become: true
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - fish-git
    - fisherman-git

- name: setup | determine shell executable location
  command: which fish
  register: fish

- name: configure | change default shell
  user: name={{ user.name }} shell={{ fish.stdout }}
  become: yes

- name: Update fisherman plugins
  shell: "fisher {{ item }}"
  args:
    executable: "{{ fish.stdout }}"
  with_items:
    - "oh-my-fish/theme-bobthefish"
    - "saratovsource/kirill0v_dev_env"
  register: fish_fisherman_plugins

