---
- name: Install base packages
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - termite
    - rofi

- name: Install aur packages
  become: true
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - dmenu
    - alacritty-scrollback-git 

- name: Copy configs directories to destanation
  copy: src={{ item }} dest="~/.config/" force=yes
  with_items:
    - i3
    - alacritty

- name: Create default config directory
  file: path=~/.i3 state=directory
  when: arch=="manjaro"

- name: Create symlink to config
  file: src=~/.config/i3/config dest=~/.i3/config state=link force=yes
  when: arch=="manjaro"

- name: Make i3exit executable
  file: dest=~/.config/i3/scripts/i3exit.sh mode=a+x
  when: arch=="manjaro"

