---
- name: Install powertop package
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - powertop

- name: Copy service config
  become: true
  copy:
    src: "powertop.service"
    dest: "/etc/systemd/system/powertop.service"

- name: Start powertop service
  become: true
  systemd:
    name: powertop
    daemon_reload: true
    state: started
    
- name: Enable powertop service at startup
  become: true
  systemd:
    name: powertop
    enabled: yes
    masked: no
