---
- name: Install acpi_call for TLP battery functions
  pacman: name=acpi_call-dkms state=present
  become: true
  tags:
    - battery

- name: Install tpacpi-bat
  become: true
  pacman: name=tpacpi-bat state=present
  tags:
    - battery

- name: Install fprintd
  become: true
  pacman: name=fprintd state=present
  tags:
    - fingerprint

- name: Push sudo authentication file
  become: true
  template: src=pam.d/sudo.j2 dest=/etc/pam.d/sudo
  tags:
    - fingerprint

- name: Push i3lock authentication file
  become: true
  template: src=pam.d/i3lock.j2 dest=/etc/pam.d/i3lock
  tags:
    - fingerprint

- name: Push trackpoint udev rules
  become: true
  copy: src=10-trackpoint.rules dest=/etc/udev/rules.d/10-trackpoint.rules
  tags:
    - trackpoint

- name: Suspend on lid switch
  become: true
  copy: src=logind.conf dest=/etc/systemd/logind.conf
  tags:
    - trackpoint

- name: Update russian keyboard layout
  become: true
  copy: src=00-keyboard.conf dest=/etc/X11/xorg.conf.d/00-keyboard.conf
  tags:
    - xkb-layout
